import { useEffect, useMemo, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import './coach-v2.css'

type Tab = 'Главная' | 'Ученики' | 'Тренировки' | 'Финансы' | 'Ещё'
type Pupil = { id: string; name: string; age: number; phone: string; group: string; fee: number; paid: number; color: string }
type Payment = { id: string; pupilId: string; amount: number; date: string }
const seed: Pupil[] = [
  { id: '1', name: 'София Иванова', age: 8, phone: '+7 900 111-22-33', group: 'Дети 7–9', fee: 2500, paid: 2500, color: '#f5c5ad' },
  { id: '2', name: 'Матвей Петров', age: 9, phone: '+7 900 234-55-66', group: 'Дети 7–9', fee: 2500, paid: 0, color: '#b9c8ed' },
  { id: '3', name: 'Алиса Смирнова', age: 12, phone: '+7 900 345-67-78', group: 'Юниоры', fee: 3000, paid: 3000, color: '#d9c1e8' },
  { id: '4', name: 'Даниил Орлов', age: 13, phone: '+7 900 456-78-89', group: 'Юниоры', fee: 3000, paid: 0, color: '#add9c7' },
]
const palette = ['#f5c5ad', '#b9c8ed', '#d9c1e8', '#add9c7', '#f1d69d']
const money = (value: number) => new Intl.NumberFormat('ru-RU').format(value) + ' ₽'
const initials = (name: string) => name.split(' ').map(x => x[0]).join('').slice(0, 2)

export default function CoachAppV2() {
  const [tab, setTab] = useState<Tab>('Главная')
  const [pupils, setPupils] = useState<Pupil[]>(() => { try { return JSON.parse(localStorage.getItem('coach-pupils') || '') } catch { return seed } })
  const [attendance, setAttendance] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('coach-attendance') || '[]') } catch { return [] } })
  const [payments, setPayments] = useState<Payment[]>(() => { try { return JSON.parse(localStorage.getItem('coach-payments') || '[]') } catch { return [] } })
  const [modal, setModal] = useState<'pupil' | 'payment' | 'edit' | null>(null)
  const [selected, setSelected] = useState<Pupil | null>(null)
  const [query, setQuery] = useState('')
  useEffect(() => localStorage.setItem('coach-pupils', JSON.stringify(pupils)), [pupils])
  useEffect(() => localStorage.setItem('coach-attendance', JSON.stringify(attendance)), [attendance])
  useEffect(() => localStorage.setItem('coach-payments', JSON.stringify(payments)), [payments])
  const totals = useMemo(() => ({ due: pupils.reduce((s,p) => s + p.fee, 0), paid: pupils.reduce((s,p) => s + p.paid, 0) }), [pupils])
  const debt = totals.due - totals.paid
  const toggleAttendance = (id: string) => setAttendance(old => old.includes(id) ? old.filter(x => x !== id) : [...old, id])
  const savePupil = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = String(data.get('name')).trim(); if (!name) return; setPupils(old => [...old, { id: crypto.randomUUID(), name, age: Number(data.get('age')) || 0, phone: String(data.get('phone')), group: String(data.get('group')) || 'Без группы', fee: Number(data.get('fee')) || 0, paid: 0, color: palette[old.length % palette.length] }]); setModal(null) }
  const addPayment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const amount = Number(new FormData(event.currentTarget).get('amount')); if (!amount || amount < 0) return; setPupils(old => old.map(p => p.id === selected.id ? { ...p, paid: Math.min(p.fee, p.paid + amount) } : p)); setPayments(old => [{ id: crypto.randomUUID(), pupilId: selected.id, amount, date: new Date().toLocaleDateString('ru-RU') }, ...old]); setModal(null); setSelected(null) }
  const editPupil = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget); setPupils(old => old.map(p => p.id === selected.id ? { ...p, name: String(data.get('name')).trim() || p.name, age: Number(data.get('age')) || 0, phone: String(data.get('phone')), group: String(data.get('group')), fee: Number(data.get('fee')) || 0 } : p)); setModal(null); setSelected(null) }
  const removePupil = () => { if (!selected || !confirm(`Удалить ученика «${selected.name}»?`)) return; setPupils(old => old.filter(p => p.id !== selected.id)); setPayments(old => old.filter(p => p.pupilId !== selected.id)); setAttendance(old => old.filter(id => id !== selected.id)); setSelected(null) }
  const openPayment = (pupil: Pupil) => { setSelected(pupil); setModal('payment') }
  const filtered = pupils.filter(p => p.name.toLowerCase().includes(query.toLowerCase()))
  return <main className="coach"><header><div className="brand"><b>К</b> Клуб</div><div className="month">Октябрь 2026</div><button className="profile">А</button></header><section className="page"><div className="heading"><div><p className="eyebrow">Пятница, 2 октября</p><h1>{tab}</h1></div>{tab === 'Ученики' && <button className="primary" onClick={() => setModal('pupil')}>＋ Добавить ученика</button>}</div>
    {tab === 'Главная' && <Dashboard pupils={pupils} totals={totals} debt={debt} attendance={attendance} toggle={toggleAttendance} onFinance={() => setTab('Финансы')} />}
    {tab === 'Ученики' && <><div className="search"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="⌕  Найти ученика"/></div><PupilList pupils={filtered} onPayment={openPayment} onSelect={setSelected}/>{selected && <PupilCard pupil={selected} payments={payments.filter(x => x.pupilId === selected.id)} onEdit={() => setModal('edit')} onPayment={() => openPayment(selected)} onClose={() => setSelected(null)} onDelete={removePupil}/>}</>}
    {tab === 'Тренировки' && <><section className="panel schedule"><p className="eyebrow">Расписание</p><h2>Сегодня, 2 октября</h2><div className="event"><b>18:00</b><span><strong>Дети 7–9 лет</strong><small>Спортивный зал · {pupils.filter(p => p.group === 'Дети 7–9').length} учеников</small></span><i>Сегодня</i></div><div className="event"><b>19:15</b><span><strong>Юниоры</strong><small>Спортивный зал · {pupils.filter(p => p.group === 'Юниоры').length} учеников</small></span><i>Сегодня</i></div></section><Attendance pupils={pupils} attendance={attendance} toggle={toggleAttendance}/></>}
    {tab === 'Финансы' && <><div className="stats"><Card label="НАЧИСЛЕНО" value={money(totals.due)} note="Октябрь 2026"/><Card label="ПОЛУЧЕНО" value={money(totals.paid)} note={`${totals.due ? Math.round(totals.paid / totals.due * 100) : 0}% от плана`}/><Card label="К ПОЛУЧЕНИЮ" value={money(debt)} note={`${pupils.filter(p => p.paid < p.fee).length} учеников`} red/></div><section className="panel"><div className="panel-title"><h2>Задолженности</h2></div><PupilList pupils={pupils.filter(p => p.paid < p.fee)} onPayment={openPayment} onSelect={setSelected}/></section></>}
    {tab === 'Ещё' && <section className="panel menu"><h2>Управление клубом</h2>{['Группы и расписание', 'Соревнования', 'Отчёты и экспорт', 'Настройки оплаты', 'Настройки профиля'].map(x => <button key={x}>◉　{x}<b>›</b></button>)}</section>}
  </section><nav>{(['Главная','Ученики','Тренировки','Финансы','Ещё'] as Tab[]).map((x,i) => <button key={x} className={tab === x ? 'active' : ''} onClick={() => setTab(x)}><span>{['⌂','♙','◷','₽','⋯'][i]}</span>{x}</button>)}</nav>
  {modal === 'pupil' && <Modal title="Новый ученик" onClose={() => setModal(null)}><form onSubmit={savePupil}><label>ФИО<input name="name" required placeholder="Например, Иван Петров"/></label><div className="form-row"><label>Возраст<input name="age" type="number" min="0" max="99" placeholder="8"/></label><label>Группа<select name="group"><option>Дети 7–9</option><option>Юниоры</option><option>Без группы</option></select></label></div><label>Телефон родителя<input name="phone" type="tel" placeholder="+7 900 000-00-00"/></label><label>Ежемесячная оплата, ₽<input name="fee" type="number" min="0" placeholder="2500" required/></label><button className="primary submit">Сохранить ученика</button></form></Modal>}
  {modal === 'payment' && selected && <Modal title={`Оплата · ${selected.name}`} onClose={() => setModal(null)}><p className="modal-note">Осталось оплатить: <b>{money(selected.fee - selected.paid)}</b></p><form onSubmit={addPayment}><label>Сумма платежа, ₽<input name="amount" type="number" min="1" max={selected.fee - selected.paid} defaultValue={selected.fee - selected.paid} required autoFocus/></label><button className="primary submit">Зачислить оплату</button></form></Modal>}
  {modal === 'edit' && selected && <Modal title="Редактировать ученика" onClose={() => setModal(null)}><form onSubmit={editPupil}><label>ФИО<input name="name" defaultValue={selected.name} required/></label><div className="form-row"><label>Возраст<input name="age" type="number" min="0" max="99" defaultValue={selected.age}/></label><label>Группа<select name="group" defaultValue={selected.group}><option>Дети 7–9</option><option>Юниоры</option><option>Без группы</option></select></label></div><label>Телефон родителя<input name="phone" defaultValue={selected.phone}/></label><label>Ежемесячная оплата, ₽<input name="fee" type="number" min="0" defaultValue={selected.fee} required/></label><button className="primary submit">Сохранить изменения</button></form></Modal>}
  </main>
}

function Card({label,value,note,red}: {label:string;value:string;note:string;red?:boolean}) { return <article className="card"><small>{label}</small><strong className={red ? 'red' : ''}>{value}</strong><em>{note}</em></article> }
function Dashboard({pupils, totals, debt, attendance, toggle, onFinance}: {pupils:Pupil[]; totals:{due:number;paid:number}; debt:number; attendance:string[];toggle:(id:string)=>void;onFinance:()=>void}) { return <><div className="stats"><Card label="СОБРАНО ЗА ОКТЯБРЬ" value={money(totals.paid)} note={`из ${money(totals.due)}`}/><Card label="УЧЕНИКОВ" value={String(pupils.length)} note="Активных учеников"/><Card label="К ПОЛУЧЕНИЮ" value={money(debt)} note="Неоплаченные абонементы" red/></div><div className="columns"><section className="panel"><div className="panel-title"><div><p className="eyebrow">Ближайшая тренировка</p><h2>Сегодня · 18:00</h2></div></div><div className="event"><b>◷</b><span><strong>Дети 7–9 лет</strong><small>Спортивный зал · 18:00–19:00</small></span><i>{pupils.length} учеников</i></div><div className="action"><span><b>Посещаемость</b><small>{attendance.length} отмечено</small></span><button className="primary" onClick={() => document.querySelector('.attendance')?.scrollIntoView({behavior:'smooth'})}>Отметить</button></div></section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Требует внимания</p><h2>Оплата</h2></div><button className="link" onClick={onFinance}>Все долги →</button></div>{pupils.filter(p => p.paid < p.fee).slice(0,2).map(p => <div className="debt" key={p.id}><Avatar pupil={p}/><span><b>{p.name}</b><small>{p.group}</small></span><strong>−{money(p.fee-p.paid)}</strong></div>)}</section></div><Attendance pupils={pupils} attendance={attendance} toggle={toggle}/></> }
function Avatar({pupil}:{pupil:Pupil}) { return <span className="avatar" style={{background:pupil.color}}>{initials(pupil.name)}</span> }
function PupilList({pupils,onPayment,onSelect}:{pupils:Pupil[];onPayment:(p:Pupil)=>void;onSelect:(p:Pupil)=>void}) { return <div className="lines">{pupils.length ? pupils.map(p => <div className="line" key={p.id}><button className="pupil-link" onClick={() => onSelect(p)}><Avatar pupil={p}/><span><b>{p.name}</b><small>{p.group} · {p.age || '—'} лет</small></span></button><i className={p.paid >= p.fee ? 'paid' : 'unpaid'}>{p.paid >= p.fee ? 'Оплачено' : `Долг ${money(p.fee-p.paid)}`}</i>{p.paid < p.fee && <button className="pay" onClick={() => onPayment(p)}>Оплатить</button>}</div>) : <p className="empty">Ничего не найдено</p>}</div> }
function PupilCard({ pupil, payments, onEdit, onPayment, onClose, onDelete }: { pupil:Pupil; payments:Payment[]; onEdit:()=>void; onPayment:()=>void; onClose:()=>void; onDelete:()=>void }) { return <section className="panel pupil-card"><div className="panel-title"><div className="card-name"><Avatar pupil={pupil}/><div><p className="eyebrow">Карточка ученика</p><h2>{pupil.name}</h2></div></div><button className="close-card" onClick={onClose}>×</button></div><div className="details"><span>Возраст<b>{pupil.age || '—'} лет</b></span><span>Группа<b>{pupil.group}</b></span><span>Телефон<b>{pupil.phone || 'Не указан'}</b></span><span>Абонемент<b>{money(pupil.fee)}</b></span></div><div className="card-actions"><button className="primary" onClick={onEdit}>Редактировать</button>{pupil.paid < pupil.fee && <button className="secondary" onClick={onPayment}>Внести оплату</button>}<button className="delete" onClick={onDelete}>Удалить</button></div><h3>История оплат</h3>{payments.length ? <div className="history">{payments.map(p => <div key={p.id}><span>{p.date}</span><b>+ {money(p.amount)}</b></div>)}</div> : <p className="empty">Платежей пока нет</p>}</section> }
function Attendance({pupils,attendance,toggle}:{pupils:Pupil[];attendance:string[];toggle:(id:string)=>void}) { return <section className="panel attendance"><div className="panel-title"><div><p className="eyebrow">Тренировка сегодня</p><h2>Отметьте присутствующих</h2></div><span className="muted">{attendance.length} отмечено</span></div><div className="student-grid">{pupils.map(p => <button className={'student ' + (attendance.includes(p.id) ? 'present' : '')} key={p.id} onClick={() => toggle(p.id)}><Avatar pupil={p}/><span><b>{p.name}</b><small>{p.age} лет</small></span><i>{attendance.includes(p.id) ? '✓' : ''}</i></button>)}</div></section> }
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) { return <div className="overlay" role="dialog" aria-modal="true"><section className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose} aria-label="Закрыть">×</button></div>{children}</section></div> }
