import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import './coach-v3.css'

type Tab = 'Главная' | 'Ученики' | 'Тренировки' | 'Финансы' | 'Ещё'
type AttendanceStatus = 'present' | 'absent' | 'sick' | 'excused' | 'makeup'
type Group = { id:string; name:string; schedule:string; hall:string; fee:number }
type Student = { id:string; name:string; birthday:string; parentPhone:string; phone:string; groupId:string; joined:string; status:'active'|'pause'|'left'; height:string; weight:string; clothes:string; note:string; color:string }
type Training = { id:string; groupId:string; date:string; time:string; cancelled:boolean; note:string }
type Attendance = { trainingId:string; studentId:string; status:AttendanceStatus }
type Payment = { id:string; studentId:string; month:string; amount:number; method:string; date:string; note:string }
type Charge = { id:string; studentId:string; month:string; amount:number; created:string }
type Competition = { id:string; name:string; date:string; place:string; fee:number; students:string[]; results:Record<string,string> }
const colors=['#f5c5ad','#b9c8ed','#d9c1e8','#add9c7','#f1d69d','#d2e0bd']
const monthKey=new Date().toISOString().slice(0,7); const today=new Date().toISOString().slice(0,10)
const seedGroups:Group[]=[{id:'g1',name:'Дети 7–9',schedule:'Вт · Чт',hall:'Спортивный зал',fee:2500},{id:'g2',name:'Юниоры',schedule:'Пн · Ср · Пт',hall:'Спортивный зал',fee:3000}]
const seedStudents:Student[]=[{id:'s1',name:'София Иванова',birthday:'2018-03-14',parentPhone:'+7 900 111-22-33',phone:'',groupId:'g1',joined:'2026-09-01',status:'active',height:'128',weight:'27',clothes:'S',note:'',color:colors[0]},{id:'s2',name:'Матвей Петров',birthday:'2017-11-20',parentPhone:'+7 900 234-55-66',phone:'',groupId:'g1',joined:'2026-09-01',status:'active',height:'132',weight:'30',clothes:'S',note:'',color:colors[1]},{id:'s3',name:'Алиса Смирнова',birthday:'2014-05-15',parentPhone:'+7 900 345-67-78',phone:'',groupId:'g2',joined:'2026-08-15',status:'active',height:'155',weight:'43',clothes:'M',note:'',color:colors[2]},{id:'s4',name:'Даниил Орлов',birthday:'2013-09-08',parentPhone:'+7 900 456-78-89',phone:'',groupId:'g2',joined:'2026-08-15',status:'active',height:'160',weight:'49',clothes:'M',note:'',color:colors[3]}]
const seedTraining:Training[]=[{id:'t1',groupId:'g1',date:today,time:'18:00',cancelled:false,note:''},{id:'t2',groupId:'g2',date:today,time:'19:15',cancelled:false,note:''}]
const load=<T,>(key:string, fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'')}catch{return fallback}}
const save=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value))
const uid=()=>crypto.randomUUID(); const money=(n:number)=>new Intl.NumberFormat('ru-RU').format(n)+' ₽'; const initials=(s:string)=>s.split(' ').map(x=>x[0]).join('').slice(0,2); const age=(date:string)=>date?Math.floor((Date.now()-new Date(date).getTime())/31557600000):0
const monthTitle=(key:string)=>new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(new Date(`${key}-01`))
const statusLabel:Record<AttendanceStatus,string>={present:'Был',absent:'Пропустил',sick:'Болел',excused:'Уважительная',makeup:'Отработка'}

export default function CoachAppV3(){
 const [tab,setTab]=useState<Tab>('Главная'),[groups,setGroups]=useState<Group[]>(()=>load('groups',seedGroups)),[students,setStudents]=useState<Student[]>(()=>load('students',seedStudents)),[trainings,setTrainings]=useState<Training[]>(()=>load('trainings',seedTraining)),[attendance,setAttendance]=useState<Attendance[]>(()=>load('attendance',[])),[payments,setPayments]=useState<Payment[]>(()=>load('payments',[])),[charges,setCharges]=useState<Charge[]>(()=>load('charges',[])),[competitions,setCompetitions]=useState<Competition[]>(()=>load('competitions',[])),[month,setMonth]=useState(monthKey),[modal,setModal]=useState<string|null>(null),[selected,setSelected]=useState<Student|null>(null),[selectedTraining,setSelectedTraining]=useState<Training|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all')
 useEffect(()=>save('groups',groups),[groups]);useEffect(()=>save('students',students),[students]);useEffect(()=>save('trainings',trainings),[trainings]);useEffect(()=>save('attendance',attendance),[attendance]);useEffect(()=>save('payments',payments),[payments]);useEffect(()=>save('charges',charges),[charges]);useEffect(()=>save('competitions',competitions),[competitions])
 const group=(id:string)=>groups.find(x=>x.id===id);const active=students.filter(x=>x.status==='active');const charge=(s:Student)=>charges.find(c=>c.studentId===s.id&&c.month===month)?.amount;const due=(s:Student)=>charge(s)??(group(s.groupId)?.fee||0);const paid=(s:Student)=>payments.filter(x=>x.studentId===s.id&&x.month===month).reduce((n,x)=>n+x.amount,0);const debt=(s:Student)=>Math.max(0,due(s)-paid(s)); const totalDue=active.reduce((n,s)=>n+due(s),0),totalPaid=active.reduce((n,s)=>n+paid(s),0)
 const updateAttendance=(trainingId:string,studentId:string,status:AttendanceStatus)=>setAttendance(old=>[...old.filter(x=>!(x.trainingId===trainingId&&x.studentId===studentId)),{trainingId,studentId,status}])
 const addStudent=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),name=String(d.get('name')).trim();if(!name)return;setStudents(x=>[...x,{id:uid(),name,birthday:String(d.get('birthday')),parentPhone:String(d.get('parentPhone')),phone:String(d.get('phone')),groupId:String(d.get('groupId')),joined:String(d.get('joined'))||today,status:'active',height:String(d.get('height')),weight:String(d.get('weight')),clothes:String(d.get('clothes')),note:String(d.get('note')),color:colors[x.length%colors.length]}]);setModal(null)}
 const editStudent=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const d=new FormData(e.currentTarget);setStudents(xs=>xs.map(s=>s.id===selected.id?{...s,name:String(d.get('name')),birthday:String(d.get('birthday')),parentPhone:String(d.get('parentPhone')),phone:String(d.get('phone')),groupId:String(d.get('groupId')),joined:String(d.get('joined')),status:String(d.get('status')) as Student['status'],height:String(d.get('height')),weight:String(d.get('weight')),clothes:String(d.get('clothes')),note:String(d.get('note'))}:s));setModal(null)}
 const addPayment=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const d=new FormData(e.currentTarget),amount=Number(d.get('amount'));if(amount<=0)return;setPayments(xs=>[{id:uid(),studentId:selected.id,month,amount,method:String(d.get('method')),date:String(d.get('date'))||today,note:String(d.get('note'))},...xs]);setModal(null)}
 const addTraining=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setTrainings(xs=>[...xs,{id:uid(),groupId:String(d.get('groupId')),date:String(d.get('date')),time:String(d.get('time')),cancelled:false,note:String(d.get('note'))}]);setModal(null)}
 const addGroup=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setGroups(xs=>[...xs,{id:uid(),name:String(d.get('name')),schedule:String(d.get('schedule')),hall:String(d.get('hall')),fee:Number(d.get('fee'))||0}]);setModal(null)}
 const addCompetition=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),ids=d.getAll('students').map(String);setCompetitions(xs=>[...xs,{id:uid(),name:String(d.get('name')),date:String(d.get('date')),place:String(d.get('place')),fee:Number(d.get('fee'))||0,students:ids,results:{}}]);setModal(null)}
 const createCharges=()=>{const newCharges=active.filter(s=>!charges.some(c=>c.studentId===s.id&&c.month===month)).map(s=>({id:uid(),studentId:s.id,month,amount:group(s.groupId)?.fee||0,created:today}));setCharges(x=>[...x,...newCharges]);alert(newCharges.length?`Создано начислений: ${newCharges.length}`:'Начисления за этот месяц уже существуют')}
 const shiftMonth=(offset:number)=>{const d=new Date(`${month}-01T12:00`);d.setMonth(d.getMonth()+offset);setMonth(d.toISOString().slice(0,7))}
 const download=()=>{const header='ФИО;Группа;Возраст;Телефон родителя;Статус;Абонемент;Оплачено;Долг\n';const rows=students.map(s=>[s.name,group(s.groupId)?.name||'',age(s.birthday),s.parentPhone,s.status,money(due(s)),money(paid(s)),money(debt(s))].join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+header+rows],{type:'text/csv'}));a.download=`клуб-${month}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const backup=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({groups,students,trainings,attendance,payments,charges,competitions},null,2)],{type:'application/json'}));a.download=`клуб-резервная-копия-${today}.json`;a.click();URL.revokeObjectURL(a.href)}
 const restore=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(String(reader.result));if(!confirm('Заменить текущие данные данными из резервной копии?'))return;setGroups(x.groups||[]);setStudents(x.students||[]);setTrainings(x.trainings||[]);setAttendance(x.attendance||[]);setPayments(x.payments||[]);setCharges(x.charges||[]);setCompetitions(x.competitions||[])}catch{alert('Не удалось прочитать файл резервной копии')}};reader.readAsText(file)}
 const reset=()=>{if(confirm('Очистить все данные приложения?')){['groups','students','trainings','attendance','payments','charges','competitions'].forEach(localStorage.remove);location.reload()}}
 return <main className="coach v3"><header><div className="brand"><b>К</b> Клуб</div><div className="month-nav"><button onClick={()=>shiftMonth(-1)}>‹</button>{monthTitle(month)}<button onClick={()=>shiftMonth(1)}>›</button></div><button className="profile">А</button></header><section className="page"><div className="heading"><div><p className="eyebrow">Офлайн-режим · данные на этом устройстве</p><h1>{tab}</h1></div>{tab==='Ученики'&&<button className="primary" onClick={()=>setModal('student')}>＋ Ученик</button>}{tab==='Тренировки'&&<button className="primary" onClick={()=>setModal('training')}>＋ Тренировка</button>}</div>
 {tab==='Главная'&&<Dashboard students={active} totalDue={totalDue} totalPaid={totalPaid} trainings={trainings.filter(x=>x.date===today)} groups={groups} attendance={attendance} onTraining={setSelectedTraining} onTab={setTab}/>} 
 {tab==='Ученики'&&<><div className="filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕  Найти ученика"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все группы</option>{groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></div><StudentList students={students.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||s.groupId===filter))} group={group} due={due} paid={paid} onSelect={setSelected}/>{selected&&<StudentCard student={selected} group={group(selected.groupId)} payments={payments.filter(p=>p.studentId===selected.id)} attendance={attendance} trainings={trainings} onEdit={()=>setModal('editStudent')} onPayment={()=>setModal('payment')} onDelete={()=>{if(confirm(`Удалить ${selected.name}?`)){setStudents(x=>x.filter(s=>s.id!==selected.id));setSelected(null)}}} onClose={()=>setSelected(null)}/>}</>}
 {tab==='Тренировки'&&<TrainingPage trainings={trainings} groups={groups} students={students} onOpen={setSelectedTraining} onCancel={id=>setTrainings(x=>x.map(t=>t.id===id?{...t,cancelled:!t.cancelled}:t))}/>} 
 {tab==='Финансы'&&<Finance students={active} due={due} paid={paid} debt={debt} totalDue={totalDue} totalPaid={totalPaid} month={month} trainings={trainings.filter(t=>t.date.startsWith(month)&&!t.cancelled)} attendance={attendance} onCreateCharges={createCharges} onSelect={setSelected}/>} 
 {tab==='Ещё'&&<More groups={groups} students={students} competitions={competitions} onGroup={()=>setModal('group')} onCompetition={()=>setModal('competition')} onExport={download} onBackup={backup} onRestore={restore} onReset={reset}/>} 
 </section><nav>{(['Главная','Ученики','Тренировки','Финансы','Ещё']as Tab[]).map((x,i)=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}><span>{['⌂','♙','◷','₽','⋯'][i]}</span>{x}</button>)}</nav>
 {selectedTraining&&<AttendanceModal training={selectedTraining} students={students.filter(s=>s.groupId===selectedTraining.groupId&&s.status==='active')} group={group(selectedTraining.groupId)} attendance={attendance} update={updateAttendance} onClose={()=>setSelectedTraining(null)}/>} 
 {modal==='student'&&<Modal title="Новый ученик" close={()=>setModal(null)}><StudentForm groups={groups} submit={addStudent}/></Modal>}{modal==='editStudent'&&selected&&<Modal title="Карточка ученика" close={()=>setModal(null)}><StudentForm groups={groups} student={selected} submit={editStudent}/></Modal>}{modal==='payment'&&selected&&<Modal title={`Оплата · ${selected.name}`} close={()=>setModal(null)}><p className="modal-note">К оплате за {monthTitle(month)}: <b>{money(debt(selected))}</b></p><form onSubmit={addPayment}><Field label="Сумма, ₽" name="amount" type="number" value={String(debt(selected))}/><Field label="Дата платежа" name="date" type="date" value={today}/><label>Способ<select name="method"><option>Перевод</option><option>Наличные</option><option>Карта</option></select></label><Field label="Комментарий" name="note"/><button className="primary submit">Зачислить платёж</button></form></Modal>}{modal==='training'&&<Modal title="Новая тренировка" close={()=>setModal(null)}><form onSubmit={addTraining}><label>Группа<select name="groupId">{groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label><Field label="Дата" name="date" type="date" value={today}/><Field label="Время" name="time" type="time" value="18:00"/><Field label="Примечание" name="note"/><button className="primary submit">Создать тренировку</button></form></Modal>}{modal==='group'&&<Modal title="Новая группа" close={()=>setModal(null)}><form onSubmit={addGroup}><Field label="Название" name="name"/><Field label="Расписание" name="schedule" placeholder="Вт · Чт"/><Field label="Зал" name="hall"/><Field label="Стоимость в месяц, ₽" name="fee" type="number"/><button className="primary submit">Создать группу</button></form></Modal>}{modal==='competition'&&<Modal title="Новое соревнование" close={()=>setModal(null)}><form onSubmit={addCompetition}><Field label="Название" name="name"/><Field label="Дата" name="date" type="date"/><Field label="Место проведения" name="place"/><Field label="Турнирный взнос, ₽" name="fee" type="number"/>{students.map(s=><label className="check" key={s.id}><input name="students" type="checkbox" value={s.id}/>{s.name}</label>)}<button className="primary submit">Добавить соревнование</button></form></Modal>}
 </main>
}
function Field({label,name,type='text',value,placeholder}:{label:string;name:string;type?:string;value?:string;placeholder?:string}){return <label>{label}<input name={name} type={type} defaultValue={value} placeholder={placeholder}/></label>}
function Avatar({s}:{s:Student}){return <span className="avatar" style={{background:s.color}}>{initials(s.name)}</span>}
function Dashboard({students,totalDue,totalPaid,trainings,groups,attendance,onTraining,onTab}:{students:Student[];totalDue:number;totalPaid:number;trainings:Training[];groups:Group[];attendance:Attendance[];onTraining:(t:Training)=>void;onTab:(t:Tab)=>void}){return <><div className="stats"><Card label="СОБРАНО ЗА МЕСЯЦ" value={money(totalPaid)} note={`из ${money(totalDue)} · ${totalDue?Math.round(totalPaid/totalDue*100):0}%`}/><Card label="УЧЕНИКОВ" value={String(students.length)} note="Активные ученики"/><Card label="К ПОЛУЧЕНИЮ" value={money(totalDue-totalPaid)} note="Текущие задолженности" red/></div><section className="panel"><div className="panel-title"><div><p className="eyebrow">Сегодня</p><h2>Тренировки</h2></div><button className="link" onClick={()=>onTab('Тренировки')}>Расписание →</button></div>{trainings.length?trainings.map(t=><button className="event clickable" key={t.id} onClick={()=>onTraining(t)}><b>{t.time}</b><span><strong>{groups.find(g=>g.id===t.groupId)?.name}</strong><small>{t.cancelled?'Отменена':`${attendance.filter(a=>a.trainingId===t.id).length} отметок`}</small></span><i>{t.cancelled?'Отмена':'Открыть'}</i></button>):<p className="empty">На сегодня тренировок нет</p>}</section></>}
function Card({label,value,note,red}:{label:string;value:string;note:string;red?:boolean}){return <article className="card"><small>{label}</small><strong className={red?'red':''}>{value}</strong><em>{note}</em></article>}
function StudentList({students,group,due,paid,onSelect}:{students:Student[];group:(id:string)=>Group|undefined;due:(s:Student)=>number;paid:(s:Student)=>number;onSelect:(s:Student)=>void}){return <section className="panel list">{students.map(s=><button className="student-line" key={s.id} onClick={()=>onSelect(s)}><Avatar s={s}/><span><b>{s.name}</b><small>{group(s.groupId)?.name||'Без группы'} · {age(s.birthday)} лет</small></span><i className={paid(s)>=due(s)?'paid':'unpaid'}>{paid(s)>=due(s)?'Оплачено':`Долг ${money(due(s)-paid(s))}`}</i><b>›</b></button>)}{!students.length&&<p className="empty">Учеников не найдено</p>}</section>}
function StudentCard({student,group,payments,attendance,trainings,onEdit,onPayment,onDelete,onClose}:{student:Student;group?:Group;payments:Payment[];attendance:Attendance[];trainings:Training[];onEdit:()=>void;onPayment:()=>void;onDelete:()=>void;onClose:()=>void}){const records=attendance.filter(a=>a.studentId===student.id),present=records.filter(a=>a.status==='present'||a.status==='makeup').length;return <section className="panel pupil-card"><div className="panel-title"><div className="card-name"><Avatar s={student}/><div><p className="eyebrow">Карточка ученика</p><h2>{student.name}</h2></div></div><button className="close-card" onClick={onClose}>×</button></div><div className="details"><span>Дата рождения<b>{student.birthday||'Не указана'} · {age(student.birthday)} лет</b></span><span>Группа<b>{group?.name||'Без группы'}</b></span><span>Родитель<b>{student.parentPhone||'Не указан'}</b></span><span>Статус<b>{student.status==='active'?'Активен':student.status==='pause'?'Пауза':'Выбыл'}</b></span><span>Рост / вес<b>{student.height||'—'} см · {student.weight||'—'} кг</b></span><span>Форма<b>{student.clothes||'—'}</b></span></div>{student.note&&<p className="note">{student.note}</p>}<div className="mini-stats"><span><b>{present}</b> посещений</span><span><b>{records.length-present}</b> пропусков</span><span><b>{records.length?Math.round(present/records.length*100):0}%</b> посещаемость</span></div><div className="card-actions"><button className="primary" onClick={onEdit}>Редактировать</button><button className="secondary" onClick={onPayment}>Оплата</button><button className="delete" onClick={onDelete}>Удалить</button></div><h3>История платежей</h3>{payments.length?<div className="history">{payments.map(p=><div key={p.id}><span>{p.date} · {p.method}</span><b>+ {money(p.amount)}</b></div>)}</div>:<p className="empty">Платежей пока нет</p>}<small className="muted">Тренировок в журнале: {trainings.filter(t=>t.groupId===student.groupId).length}</small></section>}
function TrainingPage({trainings,groups,students,onOpen,onCancel}:{trainings:Training[];groups:Group[];students:Student[];onOpen:(t:Training)=>void;onCancel:(id:string)=>void}){return <section className="panel"><div className="panel-title"><div><p className="eyebrow">Журнал тренировок</p><h2>Календарь занятий</h2></div></div>{trainings.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(t=><div className={'training-row '+(t.cancelled?'cancelled':'')} key={t.id}><span><b>{new Date(t.date+'T12:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</b><small>{t.time} · {groups.find(g=>g.id===t.groupId)?.hall}</small></span><span><strong>{groups.find(g=>g.id===t.groupId)?.name}</strong><small>{students.filter(s=>s.groupId===t.groupId&&s.status==='active').length} учеников</small></span><button className="secondary" disabled={t.cancelled} onClick={()=>onOpen(t)}>{t.cancelled?'Отменена':'Журнал'}</button><button className="icon-button" onClick={()=>onCancel(t.id)}>{t.cancelled?'↶':'×'}</button></div>)}</section>}
function AttendanceModal({training,students,group,attendance,update,onClose}:{training:Training;students:Student[];group?:Group;attendance:Attendance[];update:(t:string,s:string,status:AttendanceStatus)=>void;onClose:()=>void}){return <Modal title={`${group?.name} · ${training.date}`} close={onClose}><p className="modal-note">Выберите статус для каждого ученика. Отметки сохраняются в журнале этой тренировки.</p><div className="attendance-list">{students.map(s=>{const current=attendance.find(a=>a.trainingId===training.id&&a.studentId===s.id)?.status;return <div key={s.id}><Avatar s={s}/><b>{s.name}</b><select value={current||''} onChange={e=>update(training.id,s.id,e.target.value as AttendanceStatus)}><option value="">Не отмечен</option>{(Object.keys(statusLabel) as AttendanceStatus[]).map(k=><option value={k} key={k}>{statusLabel[k]}</option>)}</select></div>})}</div></Modal>}
function Finance({students,due,paid,debt,totalDue,totalPaid,month,trainings,attendance,onCreateCharges,onSelect}:{students:Student[];due:(s:Student)=>number;paid:(s:Student)=>number;debt:(s:Student)=>number;totalDue:number;totalPaid:number;month:string;trainings:Training[];attendance:Attendance[];onCreateCharges:()=>void;onSelect:(s:Student)=>void}){const visits=attendance.filter(a=>a.status==='present'||a.status==='makeup').length;return <><div className="stats"><Card label="НАЧИСЛЕНО" value={money(totalDue)} note={monthTitle(month)}/><Card label="ПОЛУЧЕНО" value={money(totalPaid)} note={`${totalDue?Math.round(totalPaid/totalDue*100):0}% от плана`}/><Card label="ЗАДОЛЖЕННОСТЬ" value={money(totalDue-totalPaid)} note={`${students.filter(s=>debt(s)>0).length} учеников`} red/></div><section className="panel report"><div className="panel-title"><div><p className="eyebrow">Отчёт за месяц</p><h2>{monthTitle(month)}</h2></div><button className="primary" onClick={onCreateCharges}>Начислить месяц</button></div><div className="report-grid"><span><b>{students.length}</b> учеников</span><span><b>{trainings.length}</b> тренировок</span><span><b>{visits}</b> посещений</span><span><b>{attendance.filter(a=>a.status==='absent'||a.status==='sick'||a.status==='excused').length}</b> пропусков</span></div></section><section className="panel list"><h2>Кто не оплатил</h2>{students.filter(s=>debt(s)>0).map(s=><button className="student-line" key={s.id} onClick={()=>onSelect(s)}><Avatar s={s}/><span><b>{s.name}</b><small>Оплачено {money(paid(s))} из {money(due(s))}</small></span><strong className="red">{money(debt(s))}</strong></button>)}</section></>}
function More({groups,students,competitions,onGroup,onCompetition,onExport,onBackup,onRestore,onReset}:{groups:Group[];students:Student[];competitions:Competition[];onGroup:()=>void;onCompetition:()=>void;onExport:()=>void;onBackup:()=>void;onRestore:(file?:File)=>void;onReset:()=>void}){return <><section className="panel groups"><div className="panel-title"><h2>Группы</h2><button className="primary" onClick={onGroup}>＋ Группа</button></div>{groups.map(g=><div className="group-row" key={g.id}><span><b>{g.name}</b><small>{g.schedule} · {g.hall}</small></span><i>{students.filter(s=>s.groupId===g.id&&s.status==='active').length} учеников</i><strong>{money(g.fee)}/мес</strong></div>)}</section><section className="panel groups"><div className="panel-title"><h2>Соревнования</h2><button className="primary" onClick={onCompetition}>＋ Добавить</button></div>{competitions.length?competitions.map(c=><div className="group-row" key={c.id}><span><b>{c.name}</b><small>{c.date} · {c.place||'Место не указано'}</small></span><i>{c.students.length} участников</i><strong>{money(c.fee)}</strong></div>):<p className="empty">Соревнований пока нет</p>}</section><section className="panel menu"><h2>Данные</h2><button onClick={onExport}>↥　Экспорт учеников и финансов в CSV<b>›</b></button><button onClick={onBackup}>⇩　Скачать полную резервную копию<b>›</b></button><label className="restore">⇧　Восстановить из резервной копии<input type="file" accept="application/json" onChange={e=>onRestore(e.target.files?.[0])}/><b>›</b></label><button onClick={()=>alert('Данные сохраняются только в браузере этого устройства. Скачивайте резервную копию перед сменой устройства.')}>◉　О приложении и хранении данных<b>›</b></button><button className="danger-button" onClick={onReset}>×　Очистить все данные<b>›</b></button></section></>}
function StudentForm({groups,student,submit}:{groups:Group[];student?:Student;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={submit}><Field label="ФИО" name="name" value={student?.name}/><div className="form-row"><Field label="Дата рождения" name="birthday" type="date" value={student?.birthday}/><label>Группа<select name="groupId" defaultValue={student?.groupId||groups[0]?.id}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label></div><Field label="Телефон родителя" name="parentPhone" value={student?.parentPhone}/><Field label="Телефон ученика" name="phone" value={student?.phone}/><div className="form-row"><Field label="Дата начала занятий" name="joined" type="date" value={student?.joined||today}/><label>Статус<select name="status" defaultValue={student?.status||'active'}><option value="active">Активен</option><option value="pause">Пауза</option><option value="left">Выбыл</option></select></label></div><div className="form-row"><Field label="Рост, см" name="height" value={student?.height}/><Field label="Вес, кг" name="weight" value={student?.weight}/></div><label>Размер одежды<select name="clothes" defaultValue={student?.clothes||''}><option value="">Не указан</option>{['XS','S','M','L','XL'].map(x=><option key={x}>{x}</option>)}</select></label><label>Заметка<textarea name="note" defaultValue={student?.note}/></label><button className="primary submit">Сохранить</button></form>}
function Modal({title,children,close}:{title:string;children:ReactNode;close:()=>void}){return <div className="overlay"><section className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</section></div>}
