import { useState } from 'react'
import './coach.css'

type Tab = 'Главная' | 'Ученики' | 'Тренировки' | 'Финансы' | 'Ещё'
const pupils = [
  { name: 'София Иванова', age: 8, group: 'Дети 7–9', paid: true, color: '#f5c5ad' },
  { name: 'Матвей Петров', age: 9, group: 'Дети 7–9', paid: false, color: '#b9c8ed' },
  { name: 'Алиса Смирнова', age: 12, group: 'Юниоры', paid: true, color: '#d9c1e8' },
  { name: 'Даниил Орлов', age: 13, group: 'Юниоры', paid: false, color: '#add9c7' },
]

function Avatar({ pupil }: { pupil: typeof pupils[number] }) { return <span className="avatar" style={{ background: pupil.color }}>{pupil.name.split(' ').map(x => x[0]).join('')}</span> }
function Attendance({ present, toggle }: { present: Record<string, boolean>; toggle: (name: string) => void }) { return <section className="panel attendance"><div className="panel-title"><div><p className="eyebrow">Тренировка сегодня</p><h2>Отметьте присутствующих</h2></div><span className="muted">Дети 7–9 · 18:00</span></div><div className="student-grid">{pupils.map(p => <button className={'student ' + (present[p.name] ? 'present' : '')} key={p.name} onClick={() => toggle(p.name)}><Avatar pupil={p}/><span><b>{p.name}</b><small>{p.age} лет</small></span><i>{present[p.name] ? '✓' : ''}</i></button>)}</div></section> }
function Students() { return <section className="panel list"><input placeholder="⌕  Найти ученика" />{pupils.map(p => <div className="line" key={p.name}><Avatar pupil={p}/><span><b>{p.name}</b><small>{p.group} · {p.age} лет</small></span><i className={p.paid ? 'paid' : 'unpaid'}>{p.paid ? 'Оплачено' : 'Долг 2 500 ₽'}</i><b>›</b></div>)}</section> }
function Finance() { return <><div className="stats"><Card label="НАЧИСЛЕНО" value="58 000 ₽" note="Октябрь 2026"/><Card label="ПОЛУЧЕНО" value="42 000 ₽" note="72% от плана"/><Card label="К ПОЛУЧЕНИЮ" value="16 000 ₽" note="7 учеников" red/></div><section className="panel list"><div className="panel-title"><h2>Задолженности</h2><button className="primary">＋ Платёж</button></div>{pupils.filter(p => !p.paid).map(p => <div className="line" key={p.name}><Avatar pupil={p}/><span><b>{p.name}</b><small>Срок оплаты: 1 октября</small></span><strong className="red">2 500 ₽</strong><b>›</b></div>)}</section></> }
function Card({ label, value, note, red }: { label:string; value:string; note:string; red?:boolean }) { return <article className="card"><small>{label}</small><strong className={red ? 'red' : ''}>{value}</strong><em>{note}</em></article> }
function More() { return <section className="panel menu"><h2>Управление клубом</h2>{['Группы и расписание', 'Соревнования', 'Отчёты и экспорт', 'Настройки оплаты', 'Настройки профиля'].map(x => <button key={x}>◉　{x}<b>›</b></button>)}</section> }

export default function CoachApp() {
  const [tab, setTab] = useState<Tab>('Главная'); const [present, setPresent] = useState<Record<string, boolean>>({}); const count = Object.values(present).filter(Boolean).length; const toggle = (name:string) => setPresent(old => ({...old, [name]: !old[name]}));
  let content = <><div className="stats"><Card label="СОБРАНО ЗА ОКТЯБРЬ" value="42 000 ₽" note="из 58 000 ₽ · 72%"/><Card label="УЧЕНИКОВ" value="24" note="↑ 2 новых в этом месяце"/><Card label="НЕ ОПЛАТИЛИ" value="7" note="Задолженность 16 000 ₽" red/></div><div className="columns"><section className="panel"><div className="panel-title"><div><p className="eyebrow">Ближайшая тренировка</p><h2>Сегодня · 18:00</h2></div><button className="link">Все тренировки →</button></div><div className="event"><b>◷</b><span><strong>Дети 7–9 лет</strong><small>Спортивный зал · 18:00–19:00</small></span><i>8 учеников</i></div><div className="action"><span><b>Посещаемость</b><small>{count} из 8 отмечено</small></span><button className="primary" onClick={() => document.querySelector('.attendance')?.scrollIntoView({behavior:'smooth'})}>Отметить</button></div></section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Требует внимания</p><h2>Оплата</h2></div><button className="link">Все долги →</button></div>{pupils.filter(p => !p.paid).map(p => <div className="debt" key={p.name}><Avatar pupil={p}/><span><b>{p.name}</b><small>{p.group}</small></span><strong>−2 500 ₽</strong></div>)}</section></div><Attendance present={present} toggle={toggle}/></>
  if (tab === 'Ученики') content = <Students/>; if (tab === 'Финансы') content = <Finance/>; if (tab === 'Тренировки') content = <><section className="panel schedule"><p className="eyebrow">Расписание</p><h2>Сегодня, 2 октября</h2><div className="event"><b>18:00</b><span><strong>Дети 7–9 лет</strong><small>Спортивный зал · 8 учеников</small></span><i>Сегодня</i></div><div className="event"><b>19:15</b><span><strong>Юниоры</strong><small>Спортивный зал · 10 учеников</small></span><i>Сегодня</i></div></section><Attendance present={present} toggle={toggle}/></>; if (tab === 'Ещё') content = <More/>;
  return <main><header><div className="brand"><b>К</b> Клуб</div><div className="month">‹　Октябрь 2026　›</div><button className="profile">А</button></header><section className="page"><div className="heading"><div><p className="eyebrow">Пятница, 2 октября</p><h1>{tab}</h1></div>{tab === 'Ученики' && <button className="primary">＋ Добавить ученика</button>}</div>{content}</section><nav>{(['Главная', 'Ученики', 'Тренировки', 'Финансы', 'Ещё'] as Tab[]).map((x,i) => <button className={tab===x?'active':''} onClick={() => setTab(x)} key={x}><span>{['⌂','♙','◷','₽','⋯'][i]}</span>{x}</button>)}</nav></main>
}
